language: python
python:
- "3.7"

branches:
    only:
        - master
        - develop

install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - rm miniconda.sh
    - source $HOME/miniconda/etc/profile.d/conda.sh && conda activate
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda update -q --all
    - conda config --append channels conda-forge
    - conda env create -qf env-latest.yaml;
    - source activate research;
    - unzip SDT.zip
    - mv SDT/sdtoolbox $HOME/miniconda/envs/research/lib/python3.7/site-packages
    - mv SDT/cti/* $HOME/miniconda/envs/research/lib/python3.7/site-packages/cantera/data
    - rm -rf SDT

script:
    - NUMBA_DISABLE_JIT=1
    - pytest -vv --cov=./funcs;

after_success:
    - bash <(curl -s https://codecov.io/bash)
