name: research
channels:
  - cantera
  - defaults
dependencies:
  # I don't want to troubleshoot changes in cantera!
  - cantera<2.6
  - pip>=23.0
  - python>=3.9
  - pip:
    - deepdiff
    - h5py
    - ipython
    - ipywidgets
    - jupyter
    - jupyter-contrib-nbextensions
    - jupyterlab
    - matplotlib
    - matplotlib-scalebar
    - nbconvert
    - nbformat
    - nbsphinx
    - nptdms
    - numba
    - numpy
    - pandas
    - pint
    - plotly
    - pytest
    - pytest-cov
    - pytz
    - seaborn
    - scikit-image
    - scipy
    - setuptools
    - sphinx
    - sphinx-rtd-theme
    - tables
    - tqdm
    - uncertainties
    - voila
